# This workflow will install Python dependencies, and run linters with a single version of Python
name: Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install portaudio19-dev
        pip install .[dev]
    - name: Lint imports
      run: isort --check .
    - name: Lint formatting
      run: black --check .
    - name: Lint semantics
      run: ruff .
    - name: Lint types
      run: mypy .
